/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

/**
 *
 * @author kenji
 */

import javax.swing.KeyStroke;
import javax.swing.Action;

public class CalculatorGUI extends javax.swing.JFrame {

	/**
	 * Creates new form CalculatorGUI
	 */
	public CalculatorGUI() {
		initComponents();
		InputLine = "";
	}
	private String InputLine;
	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                b1 = new javax.swing.JButton();
                b2 = new javax.swing.JButton();
                b3 = new javax.swing.JButton();
                bpl = new javax.swing.JButton();
                bmin = new javax.swing.JButton();
                b4 = new javax.swing.JButton();
                b5 = new javax.swing.JButton();
                b6 = new javax.swing.JButton();
                bmul = new javax.swing.JButton();
                bdif = new javax.swing.JButton();
                b7 = new javax.swing.JButton();
                b8 = new javax.swing.JButton();
                b9 = new javax.swing.JButton();
                bpow2 = new javax.swing.JButton();
                bpown = new javax.swing.JButton();
                b0 = new javax.swing.JButton();
                beq = new javax.swing.JButton();
                bdel = new javax.swing.JButton();
                bclear = new javax.swing.JButton();
                bsqr = new javax.swing.JButton();
                bcl = new javax.swing.JButton();
                bop = new javax.swing.JButton();
                OutputLabel = new javax.swing.JLabel();
                InputLabel = new javax.swing.JLabel();
                Consola = new javax.swing.JLabel();
                bvir = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                b1.setText("1");
                //b1.getInputMap().put( KeyStroke.getKeyStroke("1"), "InputLine += \"1\"");
                b1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                b1ActionPerformed(evt);
                        }
                });
                b1.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyPressed(java.awt.event.KeyEvent evt) {
                                b1KeyPressed(evt);
                        }
                });

                b2.setText("2");
                b2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                b2ActionPerformed(evt);
                        }
                });

                b3.setText("3");
                b3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                b3ActionPerformed(evt);
                        }
                });

                bpl.setText("+");
                bpl.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bplActionPerformed(evt);
                        }
                });

                bmin.setText("-");
                bmin.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bminActionPerformed(evt);
                        }
                });

                b4.setText("4");
                b4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                b4ActionPerformed(evt);
                        }
                });

                b5.setText("5");
                b5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                b5ActionPerformed(evt);
                        }
                });

                b6.setText("6");
                b6.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                b6ActionPerformed(evt);
                        }
                });

                bmul.setText("*");
                bmul.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bmulActionPerformed(evt);
                        }
                });

                bdif.setText("/");
                bdif.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bdifActionPerformed(evt);
                        }
                });

                b7.setText("7");
                b7.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                b7ActionPerformed(evt);
                        }
                });

                b8.setText("8");
                b8.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                b8ActionPerformed(evt);
                        }
                });

                b9.setText("9");
                b9.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                b9ActionPerformed(evt);
                        }
                });

                bpow2.setText("x^2");
                bpow2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bpow2ActionPerformed(evt);
                        }
                });

                bpown.setText("x^n");
                bpown.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bpownActionPerformed(evt);
                        }
                });

                b0.setText("0");
                b0.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                b0ActionPerformed(evt);
                        }
                });

                beq.setText("=");
                beq.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                beqActionPerformed(evt);
                        }
                });

                bdel.setText("<-");
                bdel.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bdelActionPerformed(evt);
                        }
                });

                bclear.setText("C");
                bclear.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bclearActionPerformed(evt);
                        }
                });

                bsqr.setText("sqr(x)");
                bsqr.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bsqrActionPerformed(evt);
                        }
                });

                bcl.setText(")");
                bcl.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bclActionPerformed(evt);
                        }
                });

                bop.setText("(");
                bop.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bopActionPerformed(evt);
                        }
                });

                OutputLabel.setText("=");

                InputLabel.setText("0...");

                Consola.setText("Consola");

                bvir.setText(".");
                bvir.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bvirActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(OutputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(InputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(b4)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(b5)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(b6)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(bmul)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(bdif)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(bcl))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(b7)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(b8)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(b9)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(bpow2)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(bpown))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(b0)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(beq)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(bdel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(bclear)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(bsqr))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(b1)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(b2)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(b3)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(bpl)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(bmin)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(bop)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(bvir)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(Consola, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 53, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(InputLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(b2)
                                        .addComponent(b1)
                                        .addComponent(b3)
                                        .addComponent(bpl)
                                        .addComponent(bmin)
                                        .addComponent(bop)
                                        .addComponent(bvir))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(b4)
                                        .addComponent(b5)
                                        .addComponent(b6)
                                        .addComponent(bmul)
                                        .addComponent(bdif)
                                        .addComponent(bcl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(b7)
                                        .addComponent(b8)
                                        .addComponent(b9)
                                        .addComponent(bpow2)
                                        .addComponent(bpown))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(b0)
                                        .addComponent(beq)
                                        .addComponent(bdel)
                                        .addComponent(bclear)
                                        .addComponent(bsqr))
                                .addGap(18, 18, 18)
                                .addComponent(OutputLabel)
                                .addGap(18, 18, 18)
                                .addComponent(Consola)
                                .addContainerGap(54, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
                // TODO add your handling code here:
		InputLine += "1";
		InputLabel.setText(InputLine);
        }//GEN-LAST:event_b1ActionPerformed

        private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
                // TODO add your handling code here:
		InputLine += "2";
		InputLabel.setText(InputLine);
        }//GEN-LAST:event_b2ActionPerformed

        private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
                // TODO add your handling code here:
		InputLine += "3";
		InputLabel.setText(InputLine);
        }//GEN-LAST:event_b3ActionPerformed

        private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
                // TODO add your handling code here:
		InputLine += "4";
		InputLabel.setText(InputLine);
        }//GEN-LAST:event_b4ActionPerformed

        private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
                // TODO add your handling code here:
		InputLine += "5";
		InputLabel.setText(InputLine);
        }//GEN-LAST:event_b5ActionPerformed

        private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
                // TODO add your handling code here:
		InputLine += "6";
		InputLabel.setText(InputLine);
        }//GEN-LAST:event_b6ActionPerformed

        private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
                // TODO add your handling code here:
		InputLine += "7";
		InputLabel.setText(InputLine);
        }//GEN-LAST:event_b7ActionPerformed

        private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
                // TODO add your handling code here:
		InputLine += "8";
		InputLabel.setText(InputLine);
        }//GEN-LAST:event_b8ActionPerformed

        private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
                // TODO add your handling code here:
		InputLine += "9";
		InputLabel.setText(InputLine);
        }//GEN-LAST:event_b9ActionPerformed

        private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
                // TODO add your handling code here:
		InputLine += "0";
		InputLabel.setText(InputLine);
        }//GEN-LAST:event_b0ActionPerformed

        private void beqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beqActionPerformed
                // TODO add your handling code here:
		Calculator c = new Calculator();
		//OutputLabel.setText("="+c.calc());
		OutputLabel.setText("="+c.operatie(InputLine));
		String output = "";
		byte [] ot = c.getter(InputLine.toCharArray());
		for(int i = 0; i<ot.length;i++)
		output += ot[i];
		Consola.setText(output);

		System.out.println("...");
        }//GEN-LAST:event_beqActionPerformed

        private void bdelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdelActionPerformed
                // TODO add your handling code here:
		//InputLine = "1";
        }//GEN-LAST:event_bdelActionPerformed

        private void bclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bclearActionPerformed
                // TODO add your handling code here:
		InputLine = "";
		InputLabel.setText(InputLine);
        }//GEN-LAST:event_bclearActionPerformed

        private void bsqrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsqrActionPerformed
                // TODO add your handling code here:
		InputLine += "sqr_";
		InputLabel.setText(InputLine);
        }//GEN-LAST:event_bsqrActionPerformed

        private void bplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bplActionPerformed
                // TODO add your handling code here:
		InputLine += "+";
		InputLabel.setText(InputLine);
        }//GEN-LAST:event_bplActionPerformed

        private void bminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bminActionPerformed
                // TODO add your handling code here:
		InputLine += "-";
		InputLabel.setText(InputLine);
        }//GEN-LAST:event_bminActionPerformed

        private void bmulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmulActionPerformed
                // TODO add your handling code here:
		InputLine += "*";
		InputLabel.setText(InputLine);
        }//GEN-LAST:event_bmulActionPerformed

        private void bdifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdifActionPerformed
		InputLine += "/";
                // TODO add your handling code here:
		InputLabel.setText(InputLine);
        }//GEN-LAST:event_bdifActionPerformed

        private void bpow2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpow2ActionPerformed
		InputLine += "^2";
                // TODO add your handling code here:
		InputLabel.setText(InputLine);
        }//GEN-LAST:event_bpow2ActionPerformed

        private void bpownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpownActionPerformed
		InputLine += "^";
                // TODO add your handling code here:
		InputLabel.setText(InputLine);
        }//GEN-LAST:event_bpownActionPerformed

        private void bopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bopActionPerformed
                // TODO add your handling code here:
		InputLine += "(";
		InputLabel.setText(InputLine);
        }//GEN-LAST:event_bopActionPerformed

        private void bclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bclActionPerformed
                // TODO add your handling code here:
		InputLine += ")";
		InputLabel.setText(InputLine);
        }//GEN-LAST:event_bclActionPerformed

        private void b1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b1KeyPressed
                // TODO add your handling code here:
        }//GEN-LAST:event_b1KeyPressed

        private void bvirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bvirActionPerformed
                // TODO add your handling code here:
		InputLine += ".";
		InputLabel.setText(InputLine);
        }//GEN-LAST:event_bvirActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new CalculatorGUI().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel Consola;
        private javax.swing.JLabel InputLabel;
        private javax.swing.JLabel OutputLabel;
        private javax.swing.JButton b0;
        private javax.swing.JButton b1;
        private javax.swing.JButton b2;
        private javax.swing.JButton b3;
        private javax.swing.JButton b4;
        private javax.swing.JButton b5;
        private javax.swing.JButton b6;
        private javax.swing.JButton b7;
        private javax.swing.JButton b8;
        private javax.swing.JButton b9;
        private javax.swing.JButton bcl;
        private javax.swing.JButton bclear;
        private javax.swing.JButton bdel;
        private javax.swing.JButton bdif;
        private javax.swing.JButton beq;
        private javax.swing.JButton bmin;
        private javax.swing.JButton bmul;
        private javax.swing.JButton bop;
        private javax.swing.JButton bpl;
        private javax.swing.JButton bpow2;
        private javax.swing.JButton bpown;
        private javax.swing.JButton bsqr;
        private javax.swing.JButton bvir;
        // End of variables declaration//GEN-END:variables
}
